/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EditPictureByBatch: typeof import('./src/components/EditPictureByBatch.vue')['default']
    EnlargingPictureByAi: typeof import('./src/components/EnlargingPictureByAi.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    GlobalSide: typeof import('./src/components/GlobalSide.vue')['default']
    PictureCropper: typeof import('./src/components/PictureCropper.vue')['default']
    PictureList: typeof import('./src/components/PictureList.vue')['default']
    PictureSearch: typeof import('./src/components/PictureSearch.vue')['default']
    PictureUpload: typeof import('./src/components/PictureUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareModal: typeof import('./src/components/ShareModal.vue')['default']
    SpaceCategoryAnalyzePage: typeof import('./src/components/spaceAnalyze/SpaceCategoryAnalyzePage.vue')['default']
    SpaceRankAnalyzePage: typeof import('./src/components/spaceAnalyze/SpaceRankAnalyzePage.vue')['default']
    SpaceSizeAnalyzePage: typeof import('./src/components/spaceAnalyze/SpaceSizeAnalyzePage.vue')['default']
    SpaceTagAnalyzePage: typeof import('./src/components/spaceAnalyze/SpaceTagAnalyzePage.vue')['default']
    SpaceUsageAnalyzePage: typeof import('./src/components/spaceAnalyze/SpaceUsageAnalyzePage.vue')['default']
    SpaceUserAnalyzePage: typeof import('./src/components/spaceAnalyze/SpaceUserAnalyzePage.vue')['default']
    UrlUpload: typeof import('./src/components/UrlUpload.vue')['default']
    VanCell: typeof import('vant/es')['Cell']
  }
}
